### ISSUE TITLE
confusion matrix script 

### ISSUE THREAD

**Issue by nicolebid** [UBC-MDS/Red-Wine-Quality-Prediction#36]
Hi team,  I have created the script for the confusion matrix. It requires the model (pickle file) along with the X_test and y_test csv files, so I have yet to test it locally. Once we have those files I'll test it out.

**Comment by alexzhang0825** [comment]
my function now exports the best model pipeline as a pickle file

https://github.com/UBC-MDS/Red-Wine-Quality-Prediction/pull/34
